### ISSUE TITLE
tts网址更改

### ISSUE THREAD

**Issue by 300g-BoHeYou** [skygongque/tts#15]
现在的网站是https://azure.microsoft.com/zh-cn/products/cognitive-services/text-to-speech/

**Comment by skygongque** [comment]
tampermonkey 使用这个脚本好了功能更多
```
https://greasyfork.org/zh-CN/scripts/444347-azure-speech-download/code
```
python_cli_demo 仍然可用

**Comment by skygongque** [comment]
tampermonkey版本已失效
