### ISSUE TITLE
server rejected WebSocket connection: HTTP 200

### ISSUE THREAD

**Issue by fireholder** [skygongque/tts#16]
File "tts/python_cli_demo/tts.py", line 98, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "tts/python_cli_demo/tts.py", line 57, in transferMsTTSData
    async with websockets.connect(endpoint2) as websocket:
  File "/opt/conda/lib/python3.8/site-packages/websockets/legacy/client.py", line 633, in __aenter__
    return await self
  File "/opt/conda/lib/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/opt/conda/lib/python3.8/site-packages/websockets/legacy/client.py", line 658, in __await_impl__
    await protocol.handshake(
  File "/opt/conda/lib/python3.8/site-packages/websockets/legacy/client.py", line 328, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

接口无法访问了，请问怎么处理呢

**Comment by LinZY1004** [comment]
确实不能用了

**Comment by advancejar** [comment]
不能用了，按接口数据修改后也不能用，但是用tampermonkey能下载，应该是某个参数没传上去的关系？

**Comment by chinadayang** [comment]
websockets.connect(endpoint2,extra_headers={'Origin':'https://azure.microsoft.com'})

**Comment by advancejar** [comment]
> websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))

神奇了
        headers={
        "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36","version":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
        "Connection": "Upgrade",
        "Host": "eastus.api.speech.microsoft.com",
        "Origin": "https://azure.microsoft.com",
        "Upgrade": "websocket",
        "Accept-Encoding":" gzip, deflate, br",
        "Accept-Language":" zh-CN,zh;q=0.9",
        "Cache-Control":"no-cache",
        "Pragma":" no-cache"
        }
我全加了居然不行

**Comment by xiaomihefeifei** [comment]
> > websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))
> 
> 神奇了 headers={ "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36","version":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36", "Connection": "Upgrade", "Host": "eastus.api.speech.microsoft.com", "Origin": "https://azure.microsoft.com", "Upgrade": "websocket", "Accept-Encoding":" gzip, deflate, br", "Accept-Language":" zh-CN,zh;q=0.9", "Cache-Control":"no-cache", "Pragma":" no-cache" } 我全加了居然不行

我按照上面的方法 在tts.py 59行 修改一下 可以用了

**Comment by advancejar** [comment]
> > > websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))
> > 
> > 
> > 神奇了 headers={ "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36","version":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36", "Connection": "Upgrade", "Host": "eastus.api.speech.microsoft.com", "Origin": "https://azure.microsoft.com", "Upgrade": "websocket", "Accept-Encoding":" gzip, deflate, br", "Accept-Language":" zh-CN,zh;q=0.9", "Cache-Control":"no-cache", "Pragma":" no-cache" } 我全加了居然不行
> 
> 我按照上面的方法 在tts.py 59行 修改一下 可以用了

是的，可以用，我今天把源码全读了遍，然后测试了好多参数

**Comment by cancundeyingzi** [comment]
> websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))

59行???

**Comment by cancundeyingzi** [comment]
> > > websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))
> > 
> > 
> > 神奇了 headers={ "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36","version":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36", "Connection": "Upgrade", "Host": "eastus.api.speech.microsoft.com", "Origin": "https://azure.microsoft.com", "Upgrade": "websocket", "Accept-Encoding":" gzip, deflate, br", "Accept-Language":" zh-CN,zh;q=0.9", "Cache-Control":"no-cache", "Pragma":" no-cache" } 我全加了居然不行
> 
> 我按照上面的方法 在tts.py 59行 修改一下 可以用了

57行    async with websockets.connect(endpoint2,extra_headers={'Origin':'https://azure.microsoft.com'}) as websocket:

**Comment by cancundeyingzi** [comment]
> 我按照上面的方法 在tts.py 59行 修改一下 可以用了

59???????????????????

**Comment by cancundeyingzi** [comment]
![image](https://user-images.githubusercontent.com/73635883/199739455-be8bbc48-e5e4-466f-9ffd-a7f8549cfc61.png)
注意图里48行,,我把cmd功能删了,,所以行数不对

**Comment by Linkeer365** [comment]
> websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))

改了下我好了，谢谢大佬大佬nb

**Comment by lilbeauty** [comment]
大佬6啊，我baidu找了一圈， 也没找到， 困扰我一个月，主要不太懂网络。像换了api 地址这种问题可以解决，这个问题就不会了。

**Comment by lilbeauty** [comment]
> > websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))
> 
> 改了下我好了，谢谢大佬大佬nb

6 批 6 批

**Comment by Linkeer365** [comment]
> > > websockets.connect(endpoint2,extra_headers={'Origin':'[https://azure.microsoft.com'}](https://azure.microsoft.com'%7D))
> > 
> > 
> > 神奇了 headers={ "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36","version":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36", "Connection": "Upgrade", "Host": "eastus.api.speech.microsoft.com", "Origin": "https://azure.microsoft.com", "Upgrade": "websocket", "Accept-Encoding":" gzip, deflate, br", "Accept-Language":" zh-CN,zh;q=0.9", "Cache-Control":"no-cache", "Pragma":" no-cache" } 我全加了居然不行
> 
> 我按照上面的方法 在tts.py 59行 修改一下 可以用了

兄弟，现在又开始报这个错误了，能不能帮忙看下是什么问题呀，有劳了

**Comment by skygongque** [comment]
接口已换原接口问题参考价值不大
