### ISSUE TITLE
其实不用那么麻烦，微软已经造好轮子了

### ISSUE THREAD

**Issue by kxxt** [skygongque/tts#2]
从页面上拿到 token 之后就可以直接调用微软的包了。

https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/how-to-speech-synthesis?tabs=script%2Cbrowserjs%2Cwindowsinstall&pivots=programming-language-python

我也写了个命令行小工具：https://github.com/kxxt/aspeak

**Comment by kxxt** [comment]
甚至微软官方有个示例程序：https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/python/text-to-speech/quickstart.py

**Comment by skygongque** [comment]
我知道微软有SKD，但需要key还是token之类的东西要注册账号并且绑定银行卡才给试用，没想到试用页面提取的token也可以使用SKD，很强。
这个页面没有混淆所以逆向也不麻烦，就当是练习。

**Comment by kxxt** [comment]
确实挺适合练手的😂，我不懂 Web Socket 所以就直接用的微软的 SDK
