### ISSUE TITLE
没有触发脚本

### ISSUE THREAD

**Issue by lesca** [skygongque/tts#20]
如图，地址匹配，但是没有触发脚本，脚本已经装了。

![image](https://user-images.githubusercontent.com/5976219/215933346-0b78b007-2250-4cd9-805f-1a4a4c229d0c.png)

**Comment by skygongque** [comment]
目前微软官方的demo已经移除，所以tampermonkey版本失效，但python cli版本仍然有效(使用edge在线的tts)，支持晓晓云希等常见声音，可以调节语速、声调和音量，但不支持自定义ssml，即不支持情感调节
