### ISSUE TITLE
无法支持官方定义的标签例如break

### ISSUE THREAD

**Issue by clhome** [skygongque/tts#21]
在ssml中插入类似<break time="400ms"/> 这样的标签会报错

**Comment by skygongque** [comment]
https://github.com/skygongque/tts#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
本仓库更新过接口之前是azure接口的试用，现在是edge接口，有些声音不支持
刚才添加了microsoft接口，支持部分说话风格和break标签，但该接口并不稳定
