### ISSUE TITLE
接口有次数限制，我看之前的API是可用的，如何替换？

### ISSUE THREAD

**Issue by shencp** [skygongque/tts#23]
wss://eastus.api.speech.microsoft.com/cognitiveservices/websocket/v1?TrafficType=AzureDemo&Authorization=bearer%20undefined&X-ConnectionId=577D1E595EEB45979BA26C056A519073

昨晚开始这个接口已经不能使用了，

https://www.null119.cn/index.php/archives/162/ 另外我看这款程序在用的接口，是之前本程序被淘汰的

wss://eastus.tts.speech.microsoft.com/cognitiveservices/websocket/v1

说明之前的这个接口是仍然可以使用的。

但是我没搞清楚如何替换为之前的接口。

**Comment by shencp** [comment]
找到root cause了，是因为这个接口有次数限制，怎么切换到之前的接口？

**Comment by macleo** [comment]
1、这个 Edge-TTS 还能用么？得抓包看看 Edge-TTS 用的哪个 接口了。
2、之前的接口 在哪，给个演示的 url 看看

**Comment by shencp** [comment]
> 1、这个 Edge-TTS 还能用么？得抓包看看 Edge-TTS 用的哪个 接口了。 2、之前的接口 在哪，给个演示的 url 看看

wss://eastus.tts.speech.microsoft.com/cognitiveservices/websocket/v1这个是之前的接口，不过https://www.null119.cn/index.php/archives/162/ 这个作者说这个接口已经完全被封死了。

**Comment by shencp** [comment]
> 1、这个 Edge-TTS 还能用么？得抓包看看 Edge-TTS 用的哪个 接口了。 2、之前的接口 在哪，给个演示的 url 看看

现在能发现的暂时能用的是这个chrome的插件了https://www.microsoft-tts-downloader.com/#faq 抓包应该也可以看见的，我测试发现，因该用的跟现在有次数限制的接口是一样的，多搞几次也会触发微软的限制。

**Comment by Lewislll** [comment]
您好 我这边有个对微软次数限制的解决方案，已发您邮件，希望能取得联系

**Comment by shencp** [comment]
> 1、这个 Edge-TTS 还能用么？得抓包看看 Edge-TTS 用的哪个 接口了。 2、之前的接口 在哪，给个演示的 url 看看

 Edge-TTS 肯定是可以用的，因为这个是Edge浏览器本身在用接口
