### ISSUE TITLE
20230406出错：error: server rejected WebSocket connection: HTTP 200

### ISSUE THREAD

**Issue by advancejar** [skygongque/tts#25]
error: server rejected WebSocket connection: HTTP 200
是要换接口了吗？

**Comment by advancejar** [comment]
应该是和上次一样参数不对

**Comment by ysysdzz** [comment]
有没有人来解决

**Comment by worinima2010** [comment]
求解决

**Comment by skygongque** [comment]
已经使用https://github.com/rany2/edge-tts 中的接口修复python_cli_demo版本，新接口不支持多个`voice`标签，即一次生成无法使用两种及以上声音，也可直接访问原仓库，原仓库进行了一定封装可直接作为 python的库直接使用；https://github.com/LuckyHookin/edge-TTS-record 有用户界面但也有广告（无可厚非），可以自己选择是否需要使用

**Comment by advancejar** [comment]
感谢感谢。
已经能满足我的需求了。
