### ISSUE TITLE
azureTTS收费了，各位有没有什么主意

### ISSUE THREAD

**Issue by Linkeer365** [skygongque/tts#26]
我试了下 https://github.com/rany2/edge-tts 和 https://github.com/LuckyHookin/edge-TTS-record ， 不知道是否可以成为一个不那么完美的解决方案

**Comment by skygongque** [comment]
已经使用https://github.com/rany2/edge-tts 中的接口修复python_cli_demo版本，新接口不支持多个`voice`标签，即一次生成无法使用两种及以上声音，也可直接访问原仓库，原仓库进行了一定封装可直接作为 python的库直接使用；https://github.com/LuckyHookin/edge-TTS-record 有用户界面但也有广告（无可厚非），可以自己选择是否需要使用

**Comment by ChinaChenMingQuan** [comment]
还能咋办呀，凉拌，Demo接口被关了，想用都用不了了。azure账号根本没法注册，欺负大陆没有银行卡，草！

**Comment by pendave** [comment]
> 还能咋办呀，凉拌，Demo接口被关了，想用都用不了了。azure账号根本没法注册，欺负大陆没有银行卡，草！

草+1

**Comment by advancejar** [comment]
装个chrome插件
https://www.microsoft-tts-downloader.com/#faq
f12后查询得的地址是：https://southeastasia.api.speech.microsoft.com/accfreetrial/texttospeech/acc/v3.0-beta1/vcg/speak
期望程序能改到新的程序里，虽然我暂时用不到，也为大家作福利。

**Comment by skygongque** [comment]
https://github.com/skygongque/tts#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
本仓库更新过接口之前是azure接口的试用，现在是edge接口，有些声音不支持
刚才添加了microsoft接口，支持部分说话风格，但该接口并不稳定
