### ISSUE TITLE
兄弟，有没有长文本的语音合成解决方案

### ISSUE THREAD

**Issue by leeooo001** [skygongque/tts#3]
兄弟，请教下，有没有长文本的语音合成解决方案，现在这个服务器不太稳定，基本上超过一分钟就会报错。

**Comment by pashangshangpo** [comment]
[蓝奏云-喜马拉雅文本转音频windows版](https://jscs.lanzouw.com/ieFWK05q05wj)
[蓝奏云-喜马拉雅文本转音频mac版](https://jscs.lanzouw.com/ixo2Z05q05sf) 提取码: 5f1t

**Comment by pashangshangpo** [comment]
试了一下这个，三分钟以上也没有问题

**Comment by jzhjm** [comment]
> [蓝奏云-喜马拉雅文本转音频windows版](https://jscs.lanzouw.com/ieFWK05q05wj)
> [蓝奏云-喜马拉雅文本转音频mac版](https://jscs.lanzouw.com/ixo2Z05q05sf) 提取码: 5f1t

这个 Mac 版如何使用啊？？？

**Comment by actforjason** [comment]
> [蓝奏云-喜马拉雅文本转音频windows版](https://jscs.lanzouw.com/ieFWK05q05wj) [蓝奏云-喜马拉雅文本转音频mac版](https://jscs.lanzouw.com/ixo2Z05q05sf) 提取码: 5f1t

付费的，别乱打广告

**Comment by lilbeauty** [comment]
我都是自己写个python, 把名字相同的，全是1min 左右的小mp3, 全部用ffmepg合成

**Comment by TommyRoy776** [comment]
自己寫個function 每五百字分割 只能這樣了

**Comment by pendave** [comment]
就跟google翻译一样限制5000个字每次，昨天我写了个Python脚本，有ChatGPT辅助生成的代码，分割50个<voice>元素为一组输出成_001.mp3 _002.mp3 _003.mp3 ... 然后可以合并的。

**Comment by TommyRoy776** [comment]
> 就跟google翻译一样限制5000个字每次，昨天我写了个Python脚本，有ChatGPT辅助生成的代码，分割50个元素为一组输出成_001.mp3 _002.mp3 _003.mp3 ... 然后可以合并的。

能不能搞成串流接收?? 不想完成之後一堆碎片mp3 檔案

**Comment by skygongque** [comment]
不考虑封装，不考虑长文本的语音合成
