### ISSUE TITLE
received 1007 (invalid data) SSML is invalid; then sent 1007 (invalid data) SSML is invalid

### ISSUE THREAD

**Issue by Rainfog-YW** [skygongque/tts#30]
直接使用的你里面的例子报这个错误还请您看一下

**Comment by skygongque** [comment]
使用的api更换，使用edge在线的tts的api，支持晓晓云希等常见声音，可以调节语速、声调和音量，但不支持自定义ssml，即不支持情感调节

**Comment by skygongque** [comment]
https://github.com/skygongque/tts#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
本仓库更新过接口之前是azure接口的试用，现在是edge接口，有些声音不支持
刚才添加了microsoft接口，支持部分说话风格，但该接口并不稳定
