### ISSUE TITLE
 Unsupported voice 

### ISSUE THREAD

**Issue by joseph16388** [skygongque/tts#31]
websockets.exceptions.ConnectionClosedError: received 1007 (invalid data) Unsupported voice zh-CN-XiaochenNeural.; then sent 1007 (invalid data) Unsupported voice zh-CN-XiaochenNeural.
是这个https://github.com/skygongque/tts/blob/main/python_cli_demo/readme.md列表里的很多声音目前都不支持了吗？

望回复,3Q

**Comment by skygongque** [comment]
https://github.com/skygongque/tts#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
本仓库更新过接口之前是azure接口的试用，现在是edge接口，有些声音不支持
刚才添加了microsoft接口

**Comment by joseph16388** [comment]
谢啦，**感觉微软的接口还是蛮稳定的**
