### ISSUE TITLE
这个接口不太稳定，我做了一个加强版

### ISSUE THREAD

**Issue by AndresRivas0** [skygongque/tts#35]
感谢作者大大。使用下来 **内容稍微长点，或者请求多了都会报错**。

我做了一个 [微软 文字转语音 下载器](https://www.microsoft-tts-downloader.com) 网页。在页面上可以一键下载，在界面上设置语音，也支持 原生 ssml 格式。

网址这个：
[Microsoft Text-to-Speech Downloader](https://www.microsoft-tts-downloader.com/tts)

**Comment by baobao9999** [comment]
哥你是怎么修改啊 开源给大家看看啊
